services:
  # Backend Web Service
  - type: web
    name: echoes-backend
    runtime: node
    plan: free
    buildCommand: npm run build
    startCommand: npm start
    healthCheckPath: /api/auth/me
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false # Set this in Render dashboard
      - key: JWT_SECRET
        generateValue: true # Auto-generate secure value
      - key: CLOUDINARY_CLOUD_NAME
        sync: false # Set this in Render dashboard
      - key: CLOUDINARY_API_KEY
        sync: false # Set this in Render dashboard
      - key: CLOUDINARY_API_SECRET
        sync: false # Set this in Render dashboard
      - key: FRONTEND_URL
        fromService:
          type: web
          name: echoes-frontend
          property: url

  # Static Site for Frontend
  - type: web
    name: echoes-frontend
    runtime: static
    plan: free
    buildCommand: npm run build
    staticPublishPath: ./frontend/dist
    pullRequestPreviewsEnabled: true
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

databases:
  # Optional: MongoDB database (if you want managed database)
  # - name: echoes-db
  #   databaseName: echoes
  #   user: echoes-user
